x-healthcheck_conf: &healthcheck_conf
      interval: 5s
      retries: 30

services:
  pg_isready:
    build:
      dockerfile: Dockerfile
      args:
        - TAG=${TAG:-edge}
    environment:
      - PGDIR=/var/lib/postgresql/data
      - PGDB=database
      - PGUSER=pix
      - PGPASS=pass
      - PGPORT=2345
      - PGLADDR=*
      - PGHBA=host all all all md5
      - DOCKER_DEBUG=1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pix -d database"]
      <<: *healthcheck_conf

  port_check:
    build:
      dockerfile: Dockerfile
      args:
        - TAG=${TAG:-edge}
    environment:
      - PGDIR=/var/lib/postgresql/data
      - PGDB=database
      - PGUSER=pix
      - PGPASS=pass
      - PGPORT=2345
      - PGLADDR=*
      - PGHBA=host all all all md5
      - DOCKER_DEBUG=1
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2345"]
      <<: *healthcheck_conf
